/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LiveOverlayIdRouteImport } from './routes/live/$overlayId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminModsRouteImport } from './routes/admin/mods'
import { Route as OverlayGoalOverlayIdRouteImport } from './routes/overlay/goal/$overlayId'
import { Route as LiveLikesOverlayIdRouteImport } from './routes/live/likes/$overlayId'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveOverlayIdRoute = LiveOverlayIdRouteImport.update({
  id: '/live/$overlayId',
  path: '/live/$overlayId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModsRoute = AdminModsRouteImport.update({
  id: '/admin/mods',
  path: '/admin/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayGoalOverlayIdRoute = OverlayGoalOverlayIdRouteImport.update({
  id: '/overlay/goal/$overlayId',
  path: '/overlay/goal/$overlayId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLikesOverlayIdRoute = LiveLikesOverlayIdRouteImport.update({
  id: '/live/likes/$overlayId',
  path: '/live/likes/$overlayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mods': typeof ModsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/mods': typeof AdminModsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/live/$overlayId': typeof LiveOverlayIdRoute
  '/admin': typeof AdminIndexRoute
  '/live/likes/$overlayId': typeof LiveLikesOverlayIdRoute
  '/overlay/goal/$overlayId': typeof OverlayGoalOverlayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mods': typeof ModsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/mods': typeof AdminModsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/live/$overlayId': typeof LiveOverlayIdRoute
  '/admin': typeof AdminIndexRoute
  '/live/likes/$overlayId': typeof LiveLikesOverlayIdRoute
  '/overlay/goal/$overlayId': typeof OverlayGoalOverlayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mods': typeof ModsRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/admin/mods': typeof AdminModsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/live/$overlayId': typeof LiveOverlayIdRoute
  '/admin/': typeof AdminIndexRoute
  '/live/likes/$overlayId': typeof LiveLikesOverlayIdRoute
  '/overlay/goal/$overlayId': typeof OverlayGoalOverlayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/download'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/mods'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/subscription'
    | '/admin/mods'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/live/$overlayId'
    | '/admin'
    | '/live/likes/$overlayId'
    | '/overlay/goal/$overlayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/download'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/mods'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/subscription'
    | '/admin/mods'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/live/$overlayId'
    | '/admin'
    | '/live/likes/$overlayId'
    | '/overlay/goal/$overlayId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/download'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/mods'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/subscription'
    | '/admin/mods'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/live/$overlayId'
    | '/admin/'
    | '/live/likes/$overlayId'
    | '/overlay/goal/$overlayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DownloadRoute: typeof DownloadRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ModsRoute: typeof ModsRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SubscriptionRoute: typeof SubscriptionRoute
  AdminModsRoute: typeof AdminModsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LiveOverlayIdRoute: typeof LiveOverlayIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LiveLikesOverlayIdRoute: typeof LiveLikesOverlayIdRoute
  OverlayGoalOverlayIdRoute: typeof OverlayGoalOverlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$overlayId': {
      id: '/live/$overlayId'
      path: '/live/$overlayId'
      fullPath: '/live/$overlayId'
      preLoaderRoute: typeof LiveOverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mods': {
      id: '/admin/mods'
      path: '/admin/mods'
      fullPath: '/admin/mods'
      preLoaderRoute: typeof AdminModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/goal/$overlayId': {
      id: '/overlay/goal/$overlayId'
      path: '/overlay/goal/$overlayId'
      fullPath: '/overlay/goal/$overlayId'
      preLoaderRoute: typeof OverlayGoalOverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/likes/$overlayId': {
      id: '/live/likes/$overlayId'
      path: '/live/likes/$overlayId'
      fullPath: '/live/likes/$overlayId'
      preLoaderRoute: typeof LiveLikesOverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DownloadRoute: DownloadRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ModsRoute: ModsRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SubscriptionRoute: SubscriptionRoute,
  AdminModsRoute: AdminModsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  LiveOverlayIdRoute: LiveOverlayIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  LiveLikesOverlayIdRoute: LiveLikesOverlayIdRoute,
  OverlayGoalOverlayIdRoute: OverlayGoalOverlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
