/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as ModsIndexRouteImport } from './routes/mods/index'
import { Route as GoalsIndexRouteImport } from './routes/goals/index'
import { Route as NewsNewsIdRouteImport } from './routes/news/$newsId'
import { Route as ModsModIdRouteImport } from './routes/mods/$modId'
import { Route as LiveOverlayIdRouteImport } from './routes/live/$overlayId'
import { Route as OverlayGoalOverlayIdRouteImport } from './routes/overlay/goal/$overlayId'
import { Route as LiveLikesOverlayIdRouteImport } from './routes/live/likes/$overlayId'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsIndexRoute = ModsIndexRouteImport.update({
  id: '/mods/',
  path: '/mods/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsIndexRoute = GoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsModIdRoute = ModsModIdRouteImport.update({
  id: '/mods/$modId',
  path: '/mods/$modId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveOverlayIdRoute = LiveOverlayIdRouteImport.update({
  id: '/live/$overlayId',
  path: '/live/$overlayId',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayGoalOverlayIdRoute = OverlayGoalOverlayIdRouteImport.update({
  id: '/overlay/goal/$overlayId',
  path: '/overlay/goal/$overlayId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLikesOverlayIdRoute = LiveLikesOverlayIdRouteImport.update({
  id: '/live/likes/$overlayId',
  path: '/live/likes/$overlayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/tips': typeof TipsRoute
  '/live/$overlayId': typeof LiveOverlayIdRoute
  '/mods/$modId': typeof ModsModIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/goals': typeof GoalsIndexRoute
  '/mods': typeof ModsIndexRoute
  '/news': typeof NewsIndexRoute
  '/live/likes/$overlayId': typeof LiveLikesOverlayIdRoute
  '/overlay/goal/$overlayId': typeof OverlayGoalOverlayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/tips': typeof TipsRoute
  '/live/$overlayId': typeof LiveOverlayIdRoute
  '/mods/$modId': typeof ModsModIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/goals': typeof GoalsIndexRoute
  '/mods': typeof ModsIndexRoute
  '/news': typeof NewsIndexRoute
  '/live/likes/$overlayId': typeof LiveLikesOverlayIdRoute
  '/overlay/goal/$overlayId': typeof OverlayGoalOverlayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/download': typeof DownloadRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/subscription': typeof SubscriptionRoute
  '/tips': typeof TipsRoute
  '/live/$overlayId': typeof LiveOverlayIdRoute
  '/mods/$modId': typeof ModsModIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/goals/': typeof GoalsIndexRoute
  '/mods/': typeof ModsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/live/likes/$overlayId': typeof LiveLikesOverlayIdRoute
  '/overlay/goal/$overlayId': typeof OverlayGoalOverlayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/subscription'
    | '/tips'
    | '/live/$overlayId'
    | '/mods/$modId'
    | '/news/$newsId'
    | '/goals'
    | '/mods'
    | '/news'
    | '/live/likes/$overlayId'
    | '/overlay/goal/$overlayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/subscription'
    | '/tips'
    | '/live/$overlayId'
    | '/mods/$modId'
    | '/news/$newsId'
    | '/goals'
    | '/mods'
    | '/news'
    | '/live/likes/$overlayId'
    | '/overlay/goal/$overlayId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/download'
    | '/login'
    | '/pricing'
    | '/profile'
    | '/register'
    | '/subscription'
    | '/tips'
    | '/live/$overlayId'
    | '/mods/$modId'
    | '/news/$newsId'
    | '/goals/'
    | '/mods/'
    | '/news/'
    | '/live/likes/$overlayId'
    | '/overlay/goal/$overlayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TipsRoute: typeof TipsRoute
  LiveOverlayIdRoute: typeof LiveOverlayIdRoute
  ModsModIdRoute: typeof ModsModIdRoute
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  GoalsIndexRoute: typeof GoalsIndexRoute
  ModsIndexRoute: typeof ModsIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  LiveLikesOverlayIdRoute: typeof LiveLikesOverlayIdRoute
  OverlayGoalOverlayIdRoute: typeof OverlayGoalOverlayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/': {
      id: '/mods/'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/': {
      id: '/goals/'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods/$modId': {
      id: '/mods/$modId'
      path: '/mods/$modId'
      fullPath: '/mods/$modId'
      preLoaderRoute: typeof ModsModIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$overlayId': {
      id: '/live/$overlayId'
      path: '/live/$overlayId'
      fullPath: '/live/$overlayId'
      preLoaderRoute: typeof LiveOverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/goal/$overlayId': {
      id: '/overlay/goal/$overlayId'
      path: '/overlay/goal/$overlayId'
      fullPath: '/overlay/goal/$overlayId'
      preLoaderRoute: typeof OverlayGoalOverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/likes/$overlayId': {
      id: '/live/likes/$overlayId'
      path: '/live/likes/$overlayId'
      fullPath: '/live/likes/$overlayId'
      preLoaderRoute: typeof LiveLikesOverlayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SubscriptionRoute: SubscriptionRoute,
  TipsRoute: TipsRoute,
  LiveOverlayIdRoute: LiveOverlayIdRoute,
  ModsModIdRoute: ModsModIdRoute,
  NewsNewsIdRoute: NewsNewsIdRoute,
  GoalsIndexRoute: GoalsIndexRoute,
  ModsIndexRoute: ModsIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  LiveLikesOverlayIdRoute: LiveLikesOverlayIdRoute,
  OverlayGoalOverlayIdRoute: OverlayGoalOverlayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
